service: github-webhook

package:
  exclude:
    - '*.md'
    - '.env*'
    - .serverless/**
    - 'node_modules/**'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: us-east-1
  stackTags:
    role: ${self:service}-${self:provider.stage}
    application_type: serverless
  environment:

  iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  github:
    handler: api/handlers/github.handler
    role: CodebuildInvocationRole
    events:
      - http:
          path: /api/github
          method: post
    environment:

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    httpPort: 4000

resources:
  Description: Github webhook stack
  Resources:
    CodebuildInvocationRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
                  - 'codebuild.amazonaws.com'
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: 'CodebuildInvocation'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - codebuild:StartBuild
                  Resource: 'arn:aws:codebuild:us-east-1:465213713140:project/insights-webui-angular-deploy'